name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey welcome to this repo 🤩 Congrats on your first issue on this repo 🥳 and I hope you have a great learning."
        pr-message: "Hey welcome to this repo 🤩 Congrats on your first PR ( Pull Request ) on this repo 🥳 and I hope you have a great learning."
