name: Post Merge Comment

on:
  pull_request:
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Post comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_USER: ${{ github.event.pull_request.user.login }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"body": "@${PR_USER} Thank you for your contribution! Your PR has been merged."}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments
