name: Comment and Close Issue on PR Merge

on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment-and-close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract issue number from PR body
      id: extract_issue
      run: |
        issue_number=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=Fixes #)\d+')
        echo "issue_number=$issue_number" >> $GITHUB_ENV

    - name: Comment on the merged PR
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = context.issue.number;
          const issueNumber = process.env.issue_number;
          const commentBody = `The PR has been merged successfully! 🎉 The related issue #${issueNumber} will be closed.`;

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: commentBody
          });

    - name: Close the related issue
      if: env.issue_number != ''
      uses: actions/github-script@v6
      with:
        script: |
          const issueNumber = process.env.issue_number;

          await github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            state: 'closed'
          });
