name: Assign Issue to Self

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign issue to commenter if they comment "self"
      if: github.event.comment.body == 'self'
      uses: actions/github-script@v6
      with:
        script: |
          const issueNumber = context.issue.number;
          const commenter = context.payload.comment.user.login;

          await github.issues.addAssignees({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            assignees: [commenter]
          });
